force-app/main/default/objects/Attribute_Value__c/Attribute_Value__c.object-meta.xml
<CustomObject>
    <description>Represents the benefits and values which are allowed for those benefits for a plan family</description>
    <label>Attribute Value</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attribute Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan_Benefits__c/Plan_Benefits__c.object-meta.xml
<CustomObject>
    <description>Represents the benefits which make up a plan component. Also signifies any rate driving or key benefits for a component</description>
    <label>Plan Benefits</label>
    <nameField>
        <displayFormat>PB-{000000000}</displayFormat>
        <label>Benefit Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan Benefits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan_Benefits__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <label>Plan</label>
    <referenceTo>Plan_Component__c</referenceTo>
    <relationshipLabel>Benefits</relationshipLabel>
    <relationshipName>Benefits</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Plan_Benefits__c/fields/Plan_Family__c.field-meta.xml
<CustomField>
    <fullName>Plan_Family__c</fullName>
    <formula>CASESAFEID(Plan__r.Plan_Family__c)</formula>
    <label>Plan Family</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plan_Benefits__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Benefit Value</description>
    <inlineHelpText>Benefit Value</inlineHelpText>
    <label>Value</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Attribute_Value__c.Attribute__c</field>
            <operation>equals</operation>
            <valueField>$Source.Benefit__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Attribute_Value__c</referenceTo>
    <relationshipLabel>Plan Benefits</relationshipLabel>
    <relationshipName>Plan_Benefits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan_Component__c/Plan_Component__c.object-meta.xml
<CustomObject>
    <description>Represents a grouping of attributes or benefits of a plan family. These components are used to build plan templates</description>
    <label>Plan</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan_Component__c/fields/Plan_Family__c.field-meta.xml
<CustomField>
    <fullName>Plan_Family__c</fullName>
    <label>Plan Family</label>
    <referenceTo>Plan_Family__c</referenceTo>
    <relationshipName>Plan_Components</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PlanConfigurationCtrl.cls
public with sharing class PlanConfigurationCtrl {


    private map<Id,Plan_Family__c> m_PlanFamilyById{get;set;}
    public list<SelectOption> PlanFamilies{get;set;}
    
    private map<Id, Plan_Component__c> m_BasePlanById {get;set;}
    public list<SelectOption> BasePlans{get;set;}
    
    private map<Id, Plan_Component__c> m_RiderPlanById {get;set;}
    public list<SelectOption> RiderPlans{get;set;}
    
    private map<Id, Plan_Benefits__c> m_RiderBenefitById {get;set;}
    public list<Benefit> RiderBenefits{get;set;}
    public list<Benefit> ConfiguredBenefits {get;set;}
    
    public string SelectedPlanFamilyId{get;set;}
    public string SelectedBasePlanId{get;set;}
    public string SelectedRiderPlanId{get;set;}
    
    class Benefit {
        public boolean Selected{get;set;}
        public string Plan {get;set;}
        public string Benefit {get;set;}
        public string InNetwork {get;set;}
        public string OutNetwork {get;set;}
        
        private Plan_Benefits__c m_PlanBenefit;
        
        public Benefit(string aPlan, Plan_Benefits__c aPlanBenefit)
        {
            m_PlanBenefit = aPlanBenefit;
            
            Plan = aPlan;
            Benefit = aPlanBenefit.Value__r.Attribute__r.Name;
            InNetwork = aPlanBenefit.Value__r.In_Network_Display_Value__c;
            OutNetwork = aPlanBenefit.Value__r.Out_Of_Network_Display_Value__c;
        }
    }
    
    public PlanConfigurationCtrl ()
    {
        m_PlanFamilyById = new map<Id, Plan_Family__c>([SELECT Id, Name FROM Plan_Family__c limit 100]);
        PlanFamilies = new list<SelectOption>();
        PlanFamilies.add(new SelectOption('', 'Please Select'));
        
        populateSelectOptions(m_PlanFamilyById, PlanFamilies);
              
    }
    
    private void populateSelectOptions(map<Id, sObject> aMap, list<SelectOption> aOptions)
    {
        for(Id key: aMap.Keyset())
        {
            sObject obj = aMap.get(key);
            aOptions.add(new SelectOption(obj.Id, string.valueOf(obj.get('Name'))));
        }
    }
    
    //populate BasePlanse based on SelectedPlanFamilyId
    public PageReference PopulateBasePlans()
    {
        m_BasePlanById = new map<Id, Plan_Component__c>( [SELECT Id, Name, (SELECT Id, Name, Value__r.Name, Value__r.In_Network_Display_Value__c, Value__r.Out_Of_Network_Display_Value__c, Value__r.Attribute__r.Name FROM Benefits__r) FROM Plan_Component__c WHERE Is_Base_Component__c =: true AND Product_Component_Type__c !=: 'Rider' AND Plan_Family__c =: SelectedPlanFamilyId limit 100]);   
        BasePlans = new list<SelectOption>();
        
        populateSelectOptions(m_BasePlanById, BasePlans);        
      
        return null;
    }
    
    //populate RiderPlans based on SelectedPlanFamilyId
    public PageReference PopulateRiderPlans()
    {
        m_RiderPlanById = new map<Id, Plan_Component__c>( [SELECT Id, Name, (SELECT Id, Name, Value__r.Name, Value__r.In_Network_Display_Value__c, Value__r.Out_Of_Network_Display_Value__c, Value__r.Attribute__r.Name FROM Benefits__r) FROM Plan_Component__c WHERE Is_Base_Component__c =: false AND Product_Component_Type__c =: 'Rider' AND Plan_Family__c =: SelectedPlanFamilyId limit 100]);   
        RiderPlans = new list<SelectOption>();
        
        populateSelectOptions(m_RiderPlanById, RiderPlans);
 
        return null;
    }
 
    //populate RiderPlans based on SelectedPlanFamilyId   
    public PageReference PopulateBasePlanBenefits()
    {
        Plan_Component__c selectedBasePlan = m_BasePlanById.get(SelectedBasePlanId);
        ConfiguredBenefits = new list<Benefit>();
        
        for(Plan_Benefits__c benefit : selectedBasePlan.Benefits__r)
        {
            Benefit ben = new Benefit(selectedBasePlan.Name, benefit);
            ConfiguredBenefits.add(ben);
        }
        
        //for(Plan_Benefits__c benefit = [SELECT Id, Name,(SELECT Id, Name, Value__r.Name, Value__r.In_Network_Display_Value__c, Value__r.Out_Of_Network_Display_Value__c, Value__r.Attribute__r.Name  FROM Benefits__r)  FROM Plan_Component__c WHERE Is_Base_Component__c =: false AND Product_Component_Type__c=: 'Rider' limit 100];
        
        return null;
    }
    
    //populate Benefits based on SelectedRiderPlan
    public PageReference SelectedRiderPlan()
    {
        RiderBenefits.clear();
        Plan_Component__c  selectedPlanRider = null; //get the selected rider from RiderPlans using SelectedRiderPlan
        //loop through selectedPlanRider.Plan_Benefits__r to create a list of RiderBenefit
        return null;
    }
    
     public PageReference addPlan() {
        return null;
    }


    public PageReference chooseRiderFamily() {
        return null;
    }


    public PageReference chooseBaseFamily() {
        return null;
    }


    public PageReference planFamilyChanged() {
        populateBasePlans();
        populateRiderPlans();
        //RiderBenefits = new list<Benefit>();
        //ConfiguredBenefits = new list<Benefit>();
        return null;
    }


}